# Generated by Django 3.1.3 on 2020-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20201107_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='materials',
            field=models.ManyToManyField(to='teacher.Material'),
        ),
    ]
