# Generated by Django 3.1.3 on 2020-11-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20201107_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='study_load',
        ),
        migrations.AddField(
            model_name='action',
            name='load',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
