# Generated by Django 3.1.3 on 2020-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20201109_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
