# Generated by Django 3.1.3 on 2020-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_action_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='aims',
            field=models.ManyToManyField(blank=True, to='teacher.Aim'),
        ),
        migrations.AlterField(
            model_name='action',
            name='materials',
            field=models.ManyToManyField(blank=True, to='teacher.Material'),
        ),
    ]
