# Generated by Django 3.1.3 on 2020-11-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20201109_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.week'),
            preserve_default=False,
        ),
    ]
