# Generated by Django 3.1.3 on 2020-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_action_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='splittable',
            field=models.BooleanField(default=True),
        ),
    ]
