# Generated by Django 3.1.3 on 2020-11-12 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='started',
            field=models.DateField(default=datetime.date(2020, 11, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
